# Deep Learning Homework 1
## Team Members :
#### 1) Krushika Tapedia (ktapedia)
#### 2) Janvi Kothari (jkkothari)
#### 3) Mihir Sawant (msawant)

In [1]:
import numpy as np

In [2]:
def problem1(A,B):
    print("------Problem 1-------\n")
    return print(A+B)

In [3]:
def problem2(A,B,C):
    print("------Problem 2-------\n")
    return print(np.dot(A,B)-C)

In [4]:
def problem3(A,B,C):
    print("------Problem 3-------\n")
    return print(A*B+np.matrix.transpose(C))

In [5]:
def problem4(x,y):
    print("------Problem 4------\n")
    x.shape = x.size,1
    y.shape = y.size,1
    return print("Computing x-Transpose*y \n",np.dot(np.matrix.transpose(x),y))
# We could either use np.inner or the above written statement
    

In [6]:
def problem5(A):
    print("------Problem 5-------\n")
    x,y = A.shape
    return print(np.zeros(np.ma.shape(A)))

In [7]:
def problem6(A):
    print("------Problem 6-------\n")
    x,y = np.shape(A)
    return print(np.ones(x))

In [8]:
def problem7(A):
    print("------Problem 7-------\n")
    return print(np.linalg.inv(A))

In [9]:
def problem8(A,x):
    print("------Problem 8-------\n")
    x.shape = A.shape[0],1
    return print(np.linalg.solve(A,x))

In [10]:
def problem9(A,x):
    print("------Problem 9-------\n")
    x.shape = 1,A.shape[0]
    return print(np.matrix.transpose(np.linalg.solve(np.matrix.transpose(A),np.matrix.transpose(x))))

In [11]:
def problem10(A,alpha):
    print("------Problem 10-------\n")
    return print(A+alpha*np.eye(A.shape[0],A.shape[1]))

In [12]:
def problem11(A,i,j):
    print("------Problem 11-------\n")
    return print(A[i-1,[j-1]])
# We could either do direct indexing or use the function np.item
#     return A.item(i-1,j-1)

In [13]:
def problem12(A,i):
    print("------Problem 12-------\n")
    return print(np.sum(A[i-1,:]))

In [14]:
def problem13(A,c,d):
    print("------Problem 13-------\n")
    return print(np.mean(A[np.where(np.logical_and(A>=c,A<=d))]))

In [15]:
def problem14(A,k):
    print("------Problem 14-------\n")
    x = A.shape[0]
    eigval, eigvect = np.linalg.eig(A)
#     Sorting the Eigen values and vectors to get the k largest Eigen values and Vectors
    i = eigval.argsort()[::-1]
    eigVal = eigval[i]
    eigVect = eigvect[:,i]
    l = range(0,k)
    return print(eigVect[:,l])

In [18]:
def problem15(x,k,m,s):
    print("------Problem 15-------\n")
    n = x.size
    x.shape = n,1
    z = np.array([1 for i in range(n)])
    z.shape = z.size,1
    mu = x+m*z
    sigma = np.sqrt(s*np.eye(n,n))
    return print(np.dot(sigma,np.random.randn(n,k))+mu)

In [19]:
A = np.matrix('1 2 3; 1 1 1; 3 1 2')
B = np.matrix('1 1 1; 1 0 1; 2 0 1')
C = np.matrix('1 0 1; 2 1 1; 1 1 1')
x = np.array([1,1,1])
y = np.array([1,2,3])
problem1(A,B)
problem2(A,B,C)
problem3(A,B,C)
problem4(x,y)
problem5(A)
problem6(A)
problem7(A)
problem8(A,x)
problem9(A,x)
problem10(A,5)
problem11(A,1,2)
problem12(A,1)
problem13(A,1,2)
problem14(A,2)
problem15(x,2,5,7)

------Problem 1-------

[[2 3 4]
 [2 1 2]
 [5 1 3]]
------Problem 2-------

[[8 1 5]
 [2 0 2]
 [7 2 5]]
------Problem 3-------

[[10  3  7]
 [ 4  2  4]
 [ 9  4  7]]
------Problem 4------

Computing x-Transpose*y 
 [[6]]
------Problem 5-------

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
------Problem 6-------

[ 1.  1.  1.]
------Problem 7-------

[[-0.33333333  0.33333333  0.33333333]
 [-0.33333333  2.33333333 -0.66666667]
 [ 0.66666667 -1.66666667  0.33333333]]
------Problem 8-------

[[ 0.33333333]
 [ 1.33333333]
 [-0.66666667]]
------Problem 9-------

[[ 0.  1. -0.]]
------Problem 10-------

[[ 6.  2.  3.]
 [ 1.  6.  1.]
 [ 3.  1.  7.]]
------Problem 11-------

[[2]]
------Problem 12-------

6
------Problem 13-------

1.28571428571
------Problem 14-------

[[ 0.64389561 -0.02900175]
 [ 0.31692853 -0.82883762]
 [ 0.69638693  0.55873705]]
------Problem 15-------

[[ 11.58649981   4.40429538]
 [  5.97592124   3.10383914]
 [  5.0337728    4.27942309]]
